language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - gem install jekyll
  - apt-get install pandoc
  - ./travis-tool.sh r_binary_install rjsonio
  - ./travis-tool.sh r_binary_install knitr
  - ./travis-tool.sh r_install        yaml

script: jekyll build
