language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - gem install jekyll s3_website
  - sudo apt-get install pandoc
  - ./travis-tool.sh r_binary_install rcpp rjsonio knitr ggplot2
  - ./travis-tool.sh r_install        lubridate yaml microbenchmark plyr stringr memoise inline
  - ./travis-tool.sh github_package hadley/dplyr hadley/pryr hadley/lineprof
  - ./travis-tool.sh github_package hadley/pryr

script: jekyll build

after_success:
  - s3_website push

env:
  global:
    - AWS_KEY=AKIAJYY6UT5EHUXEKWCA
    - secure: "RY3BLeRLNNPywNOnZl9gv+q30w5KzXJzpSOKwSyezteXjtXX19e95FyQ6jOP/PNdJTnjZipQPcr0v/yRaJqFK18CvkNJAMjhhiGkQP83+oWp62zdXsPNsFp6+UcmwY8XeBWINTkBqpErRYrLPoNeSzqz7z/R7trmm5/W8FHtY6o="
