language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  # Install binary pandoc from Rstudio
  - export PATH="$HOME/pandoc:$PATH"
  - mkdir pandoc
  - curl -O https://s3.amazonaws.com/rstudio-buildtools/pandoc-1.12.3.zip
  - unzip -j pandoc-1.12.3.zip pandoc-1.12.3/linux/debian/x86_64/pandoc -d pandoc
  - chmod +x pandoc/pandoc
  - pandoc --version

  # Install jekyll
  - travis_retry gem install jekyll s3_website mime-types

  # Install R packages
  - ./travis-tool.sh r_binary_install rcpp rjsonio knitr ggplot2
  - ./travis-tool.sh r_install        lubridate yaml microbenchmark dplyr plyr stringr memoise inline
  - ./travis-tool.sh github_package hadley/pryr hadley/lineprof
  - mkdir ~/.R
  - cp Makevars ~/.R

script: jekyll build

after_success:
  - s3_website push --headless

env:
  global:
    - AWS_ACCESS_KEY_ID=AKIAJYY6UT5EHUXEKWCA
    - secure: "Q0DfseEd9GJ6XcRywmje+iaA59/0OMFOMlJbOiMItrdvgHFtfhdObjGPlYg7pnBcu3xPdmHQrwJFOlUYniNOiJxi43GDRuHtHnJCacTukXwVv3e7hb+e7ZN0fHyu28putCJDxw70047bluVdsUy1SBvBcaTfg7zYjgvbnhVrnJQ="
