language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - gem install jekyll
  - sudo apt-get install pandoc
  - ./travis-tool.sh r_binary_install rcpp rjsonio knitr ggplot2
  - ./travis-tool.sh r_install        lubridate yaml microbenchmark plyr stringr memoise inline
  - ./travis-tool.sh github_package hadley/dplyr hadley/pryr hadley/lineprof
  - ./travis-tool.sh github_package hadley/pryr

script: jekyll build

deploy:
  provider: s3
  access_key_id: AKIAJYY6UT5EHUXEKWCA
  bucket: adv-r.had.co.nz.s3-website-us-west-2.amazonaws.com
  skip_cleanup: true
  local-dir: _site
  secret_access_key:
    secure: IDXI/T6LhqqGjS/mAXLjw+twE3t5RhyUwaq5pnDIMWmmEEWkTA3d0SvTi2LHwlB94hlVM68CRgtqAVJuNH16uCShnEcUrk+GeLW196VSzvLTXW1zwdWZgFDhu0Z/SPd1MnG0JDWn414YdakTclP0imaI1SRB/0eo0I45KQLscOA=
