language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - sudo apt-get install haskell-platform
  - cabal update
  - cabal install pandoc --constraint=transformers==0.3.0.0 --force-reinstalls
  - export PATH="$HOME/.cabal/bin:$PATH"
  - pandoc --version
  - travis_retry gem install jekyll s3_website
  - ./travis-tool.sh r_binary_install rcpp rjsonio knitr ggplot2
  - ./travis-tool.sh r_install        lubridate yaml microbenchmark dplyr plyr stringr memoise inline
  - ./travis-tool.sh github_package hadley/pryr hadley/lineprof
  - mkdir ~/.R
  - cp Makevars ~/.R

script: jekyll build

deploy:
  edge: true
  
  provider: s3
  access_key_id: AKIAJYY6UT5EHUXEKWCA
  secret_access_key: 
    secure: "LKoqDnr3vyBsCj6GkCBB2zTmJ81MumkyTTBki+zKin+OTsO3XcRBerAazAxfcaxZTccpSQSNDKWYcZlFMXVQMNGZ+10Cz+OAEUWk0xWML10T4V7Vc6/oXj2f0vRvizQNMgB5QmhwrOcoahgDF6EfAwG9ZVMy5Cj+7dQqMPt0yO4="
  bucket: adv-r.had.co.nz
  region: us-west-2
  skip_cleanup: true
  local-dir: _site
