language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - gem install jekyll s3_website
  - sudo apt-get install pandoc
  - ./travis-tool.sh r_binary_install rcpp rjsonio knitr ggplot2
  - ./travis-tool.sh r_install        lubridate yaml microbenchmark plyr stringr memoise inline
  - ./travis-tool.sh github_package hadley/dplyr hadley/pryr hadley/lineprof
  - ./travis-tool.sh github_package hadley/pryr

script: jekyll build

after_success:
  - s3_website push --headless

env:
  global:
    - AWS_ACCESS_KEY_ID=AKIAJYY6UT5EHUXEKWCA
    - secure: "Q0DfseEd9GJ6XcRywmje+iaA59/0OMFOMlJbOiMItrdvgHFtfhdObjGPlYg7pnBcu3xPdmHQrwJFOlUYniNOiJxi43GDRuHtHnJCacTukXwVv3e7hb+e7ZN0fHyu28putCJDxw70047bluVdsUy1SBvBcaTfg7zYjgvbnhVrnJQ="
